// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoC6haFWinV7Wjiws5QE2Ncun-aqjNcs0',
    appId: '1:750941604672:web:a95740c0971bf0e461c8a5',
    messagingSenderId: '750941604672',
    projectId: 'progrocery-4f67a',
    authDomain: 'progrocery-4f67a.firebaseapp.com',
    storageBucket: 'progrocery-4f67a.appspot.com',
    measurementId: 'G-71PPR3B7MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkvew4krNfvRUF6pIvcgBMNlXHBTFSa4',
    appId: '1:750941604672:android:d2a9c8d5a72c697d61c8a5',
    messagingSenderId: '750941604672',
    projectId: 'progrocery-4f67a',
    storageBucket: 'progrocery-4f67a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYswz-CPKRLOW9EdpsCOtrT-tDqBzmkM',
    appId: '1:750941604672:ios:ecaeccbbef3bf4c461c8a5',
    messagingSenderId: '750941604672',
    projectId: 'progrocery-4f67a',
    storageBucket: 'progrocery-4f67a.appspot.com',
    iosBundleId: 'com.example.proapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwYswz-CPKRLOW9EdpsCOtrT-tDqBzmkM',
    appId: '1:750941604672:ios:0953900ef6155c7061c8a5',
    messagingSenderId: '750941604672',
    projectId: 'progrocery-4f67a',
    storageBucket: 'progrocery-4f67a.appspot.com',
    iosBundleId: 'com.example.proapp.RunnerTests',
  );
}
